package definition_builder

import (
	"fmt"
	"os/exec"
	"strings"
	"time"

	"github.com/oriiyx/fritz/app/core/services/objects/definitions"
)

const EntitiesTableQueriesFilePathTemplate = "database/fritz"
const EntitiesAdaptersFilePathTemplate = "app/core/services/entities/adapters"

func (e *Builder) CreateCrudOperations(tablename string, d *definitions.EntityDefinition) error {
	queriesName := fmt.Sprintf("queries_%s", d.ID)
	commentBlock := "-- Code generated by fritz. DO NOT EDIT.\n" +
		fmt.Sprintf("-- Created at: %s\n", time.Now().UTC().String())

	createStatement, err := e.genCreate(tablename, d)
	if err != nil {
		return err
	}

	editStatement, err := e.genEdit(tablename, d)
	if err != nil {
		return err
	}

	readStatement, err := e.genRead(tablename, d)
	if err != nil {
		return err
	}

	deleteStatement, err := e.genDelete(tablename, d)
	if err != nil {
		return err
	}

	sql := strings.Join([]string{commentBlock, createStatement, editStatement, readStatement, deleteStatement}, "\n\n")

	err = e.cw.WriteNewFile(sql, EntitiesTableQueriesFilePathTemplate, fmt.Sprintf("%s.sql", queriesName))
	if err != nil {
		return fmt.Errorf("failed to write CRUD queries file: %w", err)
	}

	e.logger.Info().
		Str("table", tablename).
		Str("entity_id", d.ID).
		Str("file", fmt.Sprintf("%s/%s.sql", EntitiesTableQueriesFilePathTemplate, queriesName)).
		Msg("Generated CRUD operations file")

	// Run sqlc users
	cmd := exec.Command("sqlc", "users")
	output, err := cmd.CombinedOutput()
	if err != nil {
		e.logger.Error().
			Err(err).
			Str("output", string(output)).
			Msg("SQLC users failed")
		return fmt.Errorf("sqlc users failed: %w - output: %s", err, string(output))
	}

	e.logger.Info().
		Str("entity_id", d.ID).
		Msg("SQLC generation completed successfully")

	// Now users the adapter code that bridges JSON -> SQLC
	adapterCode := e.genAdapterCode(d)
	adapterFilename := e.CreateAdapterFileName(d)

	err = e.cw.WriteNewFile(adapterCode, "app/core/services/entities/adapters", adapterFilename)
	if err != nil {
		return fmt.Errorf("failed to write adapter file: %w", err)
	}

	e.logger.Info().
		Str("entity_id", d.ID).
		Str("file", fmt.Sprintf("app/core/services/entities/adapters/%s", adapterFilename)).
		Msg("Generated entity adapter")

	// Update the central loader file
	err = e.UpdateAdapterLoader(d)
	if err != nil {
		e.logger.Warn().Err(err).Msg("Failed to update adapter loader")
	}

	return nil
}

func (e *Builder) CreateAdapterFileName(d *definitions.EntityDefinition) string {
	return fmt.Sprintf("adapter_%s.go", d.ID)
}

func (e *Builder) UpdateAdapterLoader(d *definitions.EntityDefinition) error {
	entityDefinitions, err := e.LoadDefinitionsFromEntityFiles()
	if err != nil {
		return err
	}

	var code strings.Builder
	code.WriteString("// Code generated by fritz. DO NOT EDIT.\n\n")
	code.WriteString("package adapters\n\n")
	code.WriteString("import (\n")
	code.WriteString("\tdb \"github.com/oriiyx/fritz/database/generated\"\n")
	code.WriteString(")\n\n")
	code.WriteString("// LoadAll registers all entity adapters\n")
	code.WriteString("func LoadAll(queries *db.Queries) {\n")

	for _, def := range entityDefinitions {
		code.WriteString(fmt.Sprintf("\tRegister(\"%s\", New%sAdapter(queries))\n", def.ID, def.Name))
	}

	code.WriteString("}\n")

	return e.cw.WriteNewFile(code.String(), "app/core/services/entities/adapters", "loader.go")
}

func (e *Builder) genCreate(tablename string, d *definitions.EntityDefinition) (string, error) {
	queryName := fmt.Sprintf("Create%s", d.Name)
	sqlcStatement := fmt.Sprintf("-- name: %s :one", queryName)

	// Build column names and placeholders
	var columns []string
	var placeholders []string
	paramIndex := 1

	// entity_id is always required
	columns = append(columns, "entity_id")
	placeholders = append(placeholders, fmt.Sprintf("$%d", paramIndex))
	paramIndex++

	// Add each component column
	for _, component := range d.Layout.Components {
		columns = append(columns, component.Name)
		placeholders = append(placeholders, fmt.Sprintf("$%d", paramIndex))
		paramIndex++
	}

	sqlStatement := fmt.Sprintf(
		"INSERT INTO %s (%s)\nVALUES (%s)\nRETURNING *;",
		tablename,
		strings.Join(columns, ", "),
		strings.Join(placeholders, ", "),
	)

	sql := strings.Join([]string{sqlcStatement, sqlStatement}, "\n")
	return sql, nil
}

func (e *Builder) genEdit(tablename string, d *definitions.EntityDefinition) (string, error) {
	queryName := fmt.Sprintf("Update%s", d.Name)
	sqlcStatement := fmt.Sprintf("-- name: %s :one", queryName)

	// Build SET clauses
	var setClauses []string
	paramIndex := 1

	// Add each component column
	for _, component := range d.Layout.Components {
		setClauses = append(setClauses, fmt.Sprintf("%s = $%d", component.Name, paramIndex))
		paramIndex++
	}

	// Add updated_at
	setClauses = append(setClauses, "updated_at = NOW()")

	// ID is the last parameter
	idParam := paramIndex

	sqlStatement := fmt.Sprintf(
		"UPDATE %s\nSET %s\nWHERE entity_id = $%d\nRETURNING *;",
		tablename,
		strings.Join(setClauses, ", "),
		idParam,
	)

	sql := strings.Join([]string{sqlcStatement, sqlStatement}, "\n")
	return sql, nil
}

func (e *Builder) genRead(tablename string, d *definitions.EntityDefinition) (string, error) {
	queryName := fmt.Sprintf("Get%sByID", d.Name)
	sqlcStatement := fmt.Sprintf("-- name: %s :one", queryName)
	sqlStatement := fmt.Sprintf("SELECT * FROM %s WHERE entity_id = $1;", tablename)

	sql := strings.Join([]string{sqlcStatement, sqlStatement}, "\n")
	return sql, nil
}

func (e *Builder) genDelete(tablename string, d *definitions.EntityDefinition) (string, error) {
	queryName := fmt.Sprintf("Delete%s", d.Name)
	sqlcStatement := fmt.Sprintf("-- name: %s :exec", queryName)
	sqlStatement := fmt.Sprintf("DELETE FROM %s WHERE entity_id = $1;", tablename)

	sql := strings.Join([]string{sqlcStatement, sqlStatement}, "\n")
	return sql, nil
}
