// Code generated by fritz. DO NOT EDIT.

package adapters

import (
	db "github.com/oriiyx/fritz/database/generated"
)

// LoadAll registers all entity adapters
func LoadAll(queries *db.Queries) {
}
