package entity_builder

import (
	"fmt"
	"os/exec"
	"strings"
	"time"

	"github.com/oriiyx/fritz/app/core/services/objects/definitions"
)

const entitiesTableQueriesFilePathTemplate = "database/fritz"

func (e *EntityBuilder) CreateCrudOperations(tablename string, d *definitions.EntityDefinition) error {
	queriesName := fmt.Sprintf("queries_%s", d.ID)

	commentBlock := "-- Code generated by fritz. DO NOT EDIT.\n" +
		fmt.Sprintf("-- Created at: %s\n", time.Now().UTC().String())

	createStatement, err := e.genCreate(tablename, d)
	if err != nil {
		return err
	}

	editStatement, err := e.genEdit(tablename, d)
	if err != nil {
		return err
	}

	readStatement, err := e.genRead(tablename, d)
	if err != nil {
		return err
	}

	deleteStatement, err := e.genDelete(tablename, d)
	if err != nil {
		return err
	}

	sql := strings.Join([]string{commentBlock, createStatement, editStatement, readStatement, deleteStatement}, "\n\n")

	err = e.cw.WriteNewFile(sql, entitiesTableQueriesFilePathTemplate, fmt.Sprintf("%s.sql", queriesName))
	if err != nil {
		return fmt.Errorf("failed to write CRUD queries file: %w", err)
	}

	e.logger.Info().
		Str("table", tablename).
		Str("entity_id", d.ID).
		Str("file", fmt.Sprintf("%s/%s.sql", entitiesTableQueriesFilePathTemplate, queriesName)).
		Msg("Generated CRUD operations file")

	// Run sqlc generate
	cmd := exec.Command("sqlc", "generate")
	output, err := cmd.CombinedOutput()
	if err != nil {
		e.logger.Error().
			Err(err).
			Str("output", string(output)).
			Msg("SQLC generate failed")
		return fmt.Errorf("sqlc generate failed: %w - output: %s", err, string(output))
	}

	e.logger.Info().
		Str("entity_id", d.ID).
		Msg("SQLC generation completed successfully")

	return nil
}

func (e *EntityBuilder) genCreate(tablename string, d *definitions.EntityDefinition) (string, error) {
	queryName := fmt.Sprintf("Create%s", d.Name)
	sqlcStatement := fmt.Sprintf("-- name: %s :one", queryName)

	// Build column names and placeholders
	var columns []string
	var placeholders []string
	paramIndex := 1

	// entity_id is always required
	columns = append(columns, "entity_id")
	placeholders = append(placeholders, fmt.Sprintf("$%d", paramIndex))
	paramIndex++

	// Add each component column
	for _, component := range d.Layout.Components {
		columns = append(columns, component.Name)
		placeholders = append(placeholders, fmt.Sprintf("$%d", paramIndex))
		paramIndex++
	}

	sqlStatement := fmt.Sprintf(
		"INSERT INTO %s (%s)\nVALUES (%s)\nRETURNING *;",
		tablename,
		strings.Join(columns, ", "),
		strings.Join(placeholders, ", "),
	)

	sql := strings.Join([]string{sqlcStatement, sqlStatement}, "\n")
	return sql, nil
}

func (e *EntityBuilder) genEdit(tablename string, d *definitions.EntityDefinition) (string, error) {
	queryName := fmt.Sprintf("Update%s", d.Name)
	sqlcStatement := fmt.Sprintf("-- name: %s :one", queryName)

	// Build SET clauses
	var setClauses []string
	paramIndex := 1

	// Add each component column
	for _, component := range d.Layout.Components {
		setClauses = append(setClauses, fmt.Sprintf("%s = $%d", component.Name, paramIndex))
		paramIndex++
	}

	// Add updated_at
	setClauses = append(setClauses, "updated_at = NOW()")

	// ID is the last parameter
	idParam := paramIndex

	sqlStatement := fmt.Sprintf(
		"UPDATE %s\nSET %s\nWHERE id = $%d\nRETURNING *;",
		tablename,
		strings.Join(setClauses, ", "),
		idParam,
	)

	sql := strings.Join([]string{sqlcStatement, sqlStatement}, "\n")
	return sql, nil
}

func (e *EntityBuilder) genRead(tablename string, d *definitions.EntityDefinition) (string, error) {
	queryName := fmt.Sprintf("Get%sByID", d.Name)
	sqlcStatement := fmt.Sprintf("-- name: %s :one", queryName)
	sqlStatement := fmt.Sprintf("SELECT * FROM %s WHERE id = $1;", tablename)

	sql := strings.Join([]string{sqlcStatement, sqlStatement}, "\n")
	return sql, nil
}

func (e *EntityBuilder) genDelete(tablename string, d *definitions.EntityDefinition) (string, error) {
	queryName := fmt.Sprintf("Delete%s", d.Name)
	sqlcStatement := fmt.Sprintf("-- name: %s :exec", queryName)
	sqlStatement := fmt.Sprintf("DELETE FROM %s WHERE id = $1;", tablename)

	sql := strings.Join([]string{sqlcStatement, sqlStatement}, "\n")
	return sql, nil
}
